
### Export all ussuers
GET http://localhost:7071/api/issuers/export

### Export a specific issuer details
GET http://localhost:7071/api/issuers/export?Id=de891235-405e-4e72-912d-7bd51b4c92b7

### Retrieve specific issuer details
GET http://localhost:7071/api/issuers/de891235-405e-4e72-912d-7bd51b4c92b7

### Create an issuer
POST http://localhost:7071/api/issuers
Content-Type: application/json

{
    name: "Netflix, Inc"
}

### Create an issuer with validation error
POST http://localhost:7071/api/issuers
Content-Type: application/json

{
}

### Import a list of issuers
POST http://localhost:7071/api/issuers/import
Content-Type: text/csv

Name,CreatedDate
SAW Beer Pty Ltd,02/12/2020 11:33:51
Microsoft Corporation,02/11/2020 11:33:51
"Amazon.com, Inc.",02/11/2020 23:33:51


### Import a list of issuers with duplicates
POST http://localhost:7071/api/issuers/import
Content-Type: text/csv

Name,CreatedDate
Microsoft Corporation,02/12/2020 11:33:51
Microsoft Corporation,02/11/2020 11:33:51
"Amazon.com, Inc.",02/11/2020 23:33:51
"Amazon.com, Inc.",02/11/2020 23:33:51

